[tool.poetry]
name = "callback"
version = "0.1.0"
description = ""
authors = ["nelson.kanyali <nelson.kanyali@engie.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
redis = "^5.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
